name = "place-web"
main = "index.js"
compatibility_date = "2025-08-12"

[dev]
port = 80

[[kv_namespaces]]
binding = "CANVAS_STORAGE"
id = "68dc767e60e946a78246567fa025dce2"
preview_id = "2e497d287d7f42328735125355360b73"

[vars]
ENVIRONMENT = "production"

[observability.logs]
enabled = true
