name = "place-web"
main = "index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 80

[[kv_namespaces]]
binding = "CANVAS_STORAGE"
id = "68dc767e60e946a78246567fa025dce2"
preview_id = "2e497d287d7f42328735125355360b73"

[vars]
ENVIRONMENT = "production"
